### ISSUE TITLE
失效了

### ISSUE THREAD

**Issue by 3souqianting** [the-eric-kwok/GUET_Dialer_New#2]
拨号的ip变了
运营商放的位置也变了

**Comment by the-eric-kwok** [comment]
你知道现在的拨号 IP 吗？
如果你有没拨上号的设备，连接到校园网后访问 http://sina.com 就会被跳转到拨号页面，把 IP 复制给我一下，谢谢啦

**Comment by the-eric-kwok** [comment]
新的 IP 为 10.0.1.5

**Comment by the-eric-kwok** [comment]
Closed #3
