### ISSUE TITLE
无法连接网络

### ISSUE THREAD

**Issue by AndPuQing** [the-eric-kwok/GUET_Dialer_New#6]
设备：raspberrypi
运行dial.sh login 返回resual:1但是无法连接网络
![image](https://user-images.githubusercontent.com/27223114/131441197-00e76fc6-aac5-4b3a-88ec-e3e4da8c4441.png)
这是返回值

**Comment by the-eric-kwok** [comment]
我这边没有遇到这个问题，你可以提供一些具体的信息吗？是树莓派连网线直接登录并作为热点来共享Wi-Fi还是树莓派挂在路由器下面跑脚本登录呢？

**Comment by AndPuQing** [comment]
已解决该问题，改用了get方法认证

**Comment by the-eric-kwok** [comment]
嗯？我的代码原文也是使用的get方法呀
可以详细说明一下改动的地方嘛？十分感谢

**Comment by AndPuQing** [comment]
我开源了，见仓库

**Comment by the-eric-kwok** [comment]
噢！你用 Python 重写了！
我这个脚本在路由器上跑，路由器内存太小了跑不起 Python，所以没有用 Python 来写。
既然如此那我就关闭这个 issue 咯！感谢支持！
